In [109]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn import metrics

In [89]:
train = pd.read_csv('./data/train.csv', encoding = "utf-8", dtype = {'type': np.int32})
test = pd.read_csv('./data/test.csv', encoding = "utf-8")

In [90]:
spices={'1': 'Iris-setosa', '2': 'Iris-versicolor', '3': 'Iris-virginica', '4': 'Iris-new_type'}

In [117]:
train.fillna(0, inplace=True)
temp = np.array(train.values.tolist()) #將dataframe變換成np_array的type
x, y = np.array(temp[:,1:5],dtype=np.float64), np.array(temp[:,-1],dtype=np.float64) #將資料切割成我們要的形式，並將其轉換成float以方便計算
print(x) #印出來檢查
print(y[:3])

[[5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.

In [118]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=35, shuffle=True)
#將已標好標籤的資料切割成train和test，以方便測驗自己的準確度，也可幫助避免overfitting的問題

In [119]:
model = LinearSVC(random_state=0) #選用LinearSVC做model
model.fit(x_train, y_train) #學習

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=0)

In [120]:
predictions = model.predict(x_train) #用train過的資料做預測
print(metrics.mean_squared_error(y_train,predictions)) #看看錯誤率
predictions = model.predict(x_test) #用之前分割出來的test資料
print(metrics.mean_squared_error(y_test,predictions)) #看看錯誤率

0.06521739130434782
0.0967741935483871


In [126]:
test_array = np.array(test.values.tolist(),dtype=np.float64)[:,1:5] #將沒有標籤的data做好處理以方便預測
print(test_array[:3]) #試著印看看

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [167]:
predict = model.predict(test_array) #預測沒有標籤的資料
print("answer: " + str(predict)) 
answer = [[i+1,int(predict[i])] for i in range(len(predict))] #將答案與id合併，id從1開始，固i+1
print("answer_with_id: " + str(answer) )

answer: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3.]


IndexError: index 30 is out of bounds for axis 0 with size 30

In [160]:
import csv
header = ["id", "type"] #submission所要的標題
with open('./submission.csv', 'w', newline='') as myfile: #以write模式開啟指定csv檔，newline時不需要換行，因為已經使用writerow
    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)#指定要write的檔案，前面已經open的檔案當作myfile故直接write myfile
    wr.writerow(header) #先write標題
    for i in answer: 
        wr.writerow(i) #依序write每一組值